// Login Auth action type.
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const LOGIN_FAILD = "LOGIN_FAILD";

// admin setting action type.
// designation action type.
export const GET_DESIGNATION = "GET_DESIGNATION";
export const GET_DESIGNATION_SUCCESS = "GET_DESIGNATION_SUCCESS";
export const ADD_DESIGINATION = "ADD_DESIGINATION";
export const ADD_DESIGINATION_SUCCESS = "ADD_DESIGINATION_SUCCESS";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";
export const UPDATE_DESIGNATION_SUCCESS = "UPDATE_DESIGNATION_SUCCESS";
export const DEL_DESIGNATION = "DEL_DESIGNATION";
export const DEL_DESIGNATION_SUCCESS = "DEL_DESIGNATION_SUCCESS";

// department action type.
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";

// work permise.
export const GET_WORKPRIMISE = "GET_WORKPRIMISE";
export const GET_WORKPRIMISE_SUCCESS = "GET_WORKPRIMISE_SUCCESS";
export const ADD_WORKPRIMISE = "ADD_WORKPRIMISE";
export const ADD_WORKPRIMISE_SUCCESS = "ADD_WORKPRIMISE_SUCCESS";
export const UPDATE_WORKPRIMISE = "UPDATE_WORKPRIMISE";
export const UPDATE_WORKPRIMISE_SUCCESS = "UPDATE_WORKPRIMISE_SUCCESS";
export const DEL_WORKPRIMISE = "DEL_WORKPRIMISE";
export const DEL_WORKPRIMISE_SUCCESS = "DEL_WORKPRIMISE_SUCCESS";
// reward.
export const GET_REWARDS = "GET_REWARDS";
export const GET_REWARDS_SUCCESS = "GET_REWARDS_SUCCESS";
export const ADD_REWARDS = "ADD_REWARDS";
export const ADD_REWARDS_SUCCESS = "ADD_REWARDS_SUCCESS";
export const UPDATE_REWARDS = "UPDATE_REWARDS";
export const UPDATE_REWARDS_SUCCESS = "UPDATE_REWARDS_SUCCESS";
export const DEL_REWADRDS = "DEL_REWADRDS";
export const DEL_REWADRDS_SUCCESS = "DEL_REWADRDS_SUCCESS";
// officeLocation action type.
export const GET_OFFICELOCATION = "GET_OFFICELOCATION";
export const GET_OFFICELOCATION_SUCCESS = "GET_OFFICELOCATION_SUCCESS";
export const ADD_OFFICELOCATION = "ADD_OFFICELOCATION";
export const ADD_OFFICELOCATION_SUCCESS = "ADD_OFFICELOCATION_SUCCESS";
export const UPDATE_OFFICELOCATION = "UPDATE_OFFICELOCATION";
export const UPDATE_OFFICELOCATION_SUCCESS = "UPDATE_OFFICELOCATION_SUCCESS";
export const DEL_OFFICELOCATION = "DEL_OFFICELOCATION";
export const DEL_OFFICELOCATION_SUCCESS = "DEL_OFFICELOCATION_SUCCESS";
// asset action type.
export const GET_SELECTED_ASSET = "GET_SELECTED_ASSET";
export const GET_ASSET = "GET_ASSET";
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS";
export const ADD_ASSET = "ADD_ASSET";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const DEL_ASSET = "DEL_ASSET";
export const DEL_ASSET_SUCCESS = "DEL_ASSET_SUCCESS";

// Item action type.
export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const ADD_ITEM = "ADD_ITEM";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const DEL_ITEM = "DEL_ITEM";
export const DEL_ITEM_SUCCESS = "DEL_ITEM_SUCCESS";

// Certification.
export const GET_CERTIFICATIONS = "GET_CERTIFICATIONS";
export const GET_CERTIFICATIONS_SUCCESS = "GET_CERTIFICATIONS_SUCCESS";

// admin setting action type  END.

// Process rewards action type.
export const GET_PROCESS_REWARDS = "GET_PROCESS_REWARDS";
export const GET_PROCESS_REWARDS_SUCCESS = "GET_PROCESS_REWARDS_SUCCESS";

// Task action type.

export const GET_EMP_WORKING_PROJECTS = "GET_EMP_WORKING_PROJECTS";
export const GET_EMP_WORKING_PROJECTS_SUCCESS =
  "GET_EMP_WORKING_PROJECTS_SUCCESS";

export const GET_EMP_TASK = "GET_EMP_TASK";
export const GET_EMP_TASK_SUCCESS = "GET_EMP_TASK_SUCCESS";
export const GET_ALL_TASK_OF_PROJECT = "GET_ALL_TASK_OF_PROJECT";
export const GET_ALL_TASK_OF_PROJECT_SUCCESS =
  "GET_ALL_TASK_OF_PROJECT_SUCCESS";
export const GET_PROJECT_ID_TASK = "GET_PROJECT_ID_TASK";
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const DEL_TASK = "DEL_TASK";
export const DEL_TASK_SUCCESS = "DEL_TASK_SUCCESS";
export const ON_CHANGE_TASK_DATE = "ON_CHANGE_TASK_DATE";
export const ADD_PROJECT_FROM_TASK = "ADD_PROJECT_FROM_TASK";

// Employee Type action type.
export const GET_EMPLOYEETYPE_LIST = "GET_EMPLOYEETYPE_LIST";
export const GET_EMPLOYEETYPE_LIST_SUCCESS = "GET_EMPLOYEETYPE_LIST_SUCCESS";
export const GET_EMPLOYEETYPES_BY_ID = "GET_EMPLOYEETYPES_BY_ID";
export const GET_EMPLOYEETYPES_BY_ID_SUCCESS =
  "GET_EMPLOYEETYPES_BY_ID_SUCCESS";
export const ADD_EMPLOYEETYPE = "ADD_EMPLOYEETYPE";
export const ADD_EMPLOYEETYPE_SUCCESS = "ADD_EMPLOYEETYPE_SUCCESS";
export const UPDATE_EMPLOYEETYPE = "UPDATE_EMPLOYEETYPE";
export const UPDATE_EMPLOYEETYPE_SUCCESS = "UPDATE_EMPLOYEETYPE_SUCCESS";
export const DELETE_EMPLOYEETYPE = "DELETE_EMPLOYEETYPE";
export const DELETE_EMPLOYEETYPE_SUCCESS = "DELETE_EMPLOYEETYPE_SUCCESS";

// Employee action type.
export const GET_EMP_LIST = "GET_EMP_LIST";
export const GET_EMP_LIST_SUCCESS = "GET_EMP_LIST_SUCCESS";
export const ADD_EMP = "ADD_EMP";
export const ADD_EMP_SUCCESS = "ADD_EMP_SUCCESS";
export const DEL_EMP = "DEL_EMP";
export const DEL_EMP_SUCCESS = "DEL_EMP_SUCCESS";
export const UPDATE_EMP = "UPDATE_EMP";
export const UPDATE_EMP_SUCCESS = "UPDATE_EMP_SUCCESS";

export const GET_SELECT_EMP = "GET_SELECT_EMP";
export const GET_SELECT_EMP_SUCCESS = "GET_SELECT_EMP_SUCCESS";

export const GET_EMP_CERTIFICATE = "GET_EMP_CERTIFICATE";
export const GET_EMP_CERTIFICATE_SUCCESS = "GET_EMP_CERTIFICATE_SUCCESS";
export const ADD_EMP_CERTIFICATE = "ADD_EMP_CERTIFICATE";
export const ADD_EMP_CERTIFICATE_SUCCESS = "ADD_EMP_CERTIFICATE_SUCCESS";
export const UPDATE_EMP_CERTIFICATE = "UPDATE_EMP_CERTIFICATE";
export const UPDATE_EMP_CERTIFICATE_SUCCESS = "UPDATE_EMP_CERTIFICATE_SUCCESS";
export const DEL_EMP_CERTIFICATE = "DEL_EMP_CERTIFICATE";
export const DEL_EMP_CERTIFICATE_SUCCESS = "DEL_EMP_CERTIFICATE_SUCCESS";

export const GET_EMP_SKILL = "GET_EMP_SKILL";
export const GET_EMP_SKILL_SUCCESS = "GET_EMP_SKILL_SUCCESS";
export const ADD_EMP_SKILL = "ADD_EMP_SKILL";
export const ADD_EMP_SKILL_SUCCESS = "ADD_EMP_SKILL_SUCCESS";
export const DEL_EMP_SKILL = "DEL_EMP_SKILL";
export const DEL_EMP_SKILL_SUCCESS = "DEL_EMP_SKILL_SUCCESS";

//Leave Types
export const GET_LEAVETYPES = "GET_LEAVETYPES";
export const GET_LEAVETYPES_SUCCESS = "GET_LEAVETYPES_SUCCESS";
export const ADD_LEAVETYPES = "ADD_LEAVETYPES";
export const ADD_LEAVETYPES_SUCCESS = "ADD_LEAVETYPES_SUCCESS";
export const UPDATE_LEAVETYPES = "UPDATE_LEAVETYPES";
export const UPDATE_LEAVETYPES_SUCCESS = "UPDATE_LEAVETYPES_SUCCESS";
export const DELETE_LEAVETYPES = "DELETE_LEAVETYPES";
export const DELETE_LEAVETYPES_SUCCESS = "DELETE_LEAVETYPES_SUCCESS";

// Company Policies
export const GET_COMPANY_PLOICIES = "GET_COMPANY_PLOICIES";
export const GET_COMPANY_PLOICIES_SUCCESS = "GET_COMPANY_PLOICIES_SUCCESS";
export const ADD_COMPANY_PLOICIES = "ADD_COMPANY_PLOICIES";
export const ADD_COMPANY_PLOICIES_SUCCESS = "ADD_COMPANY_PLOICIES_SUCCESS";
export const UPDATE_COMPANY_PLOICIES = "UPDATE_COMPANY_PLOICIES";
export const UPDATE_COMPANY_PLOICIES_SUCCESS =
  "UPDATE_COMPANY_PLOICIES_SUCCESS";
export const DELETE_COMPANY_PLOICIES = "DELETE_COMPANY_PLOICIES";
export const DELETE_COMPANY_PLOICIES_SUCCESS =
  "DELETE_COMPANY_PLOICIES_SUCCESS";

// Holiday Calendar
export const GET_HOLIDAY_CALENDAR = "GET_HOLIDAY_CALENDAR";
export const GET_HOLIDAY_CALENDAR_SUCCESS = "GET_HOLIDAY_CALENDAR_SUCCESS";
export const ADD_HOLIDAY_CALENDAR = "ADD_HOLIDAY_CALENDAR";
export const ADD_HOLIDAY_CALENDAR_SUCCESS = "ADD_HOLIDAY_CALENDAR_SUCCESS";
export const UPDATE_HOLIDAY_CALENDAR = "UPDATE_HOLIDAY_CALENDAR";
export const UPDATE_HOLIDAY_CALENDAR_SUCCESS =
  "UPDATE_HOLIDAY_CALENDAR_SUCCESS";
export const DELETE_HOLIDAY_CALENDAR = "DELETE_HOLIDAY_CALENDAR";
export const DELETE_HOLIDAY_CALENDAR_SUCCESS =
  "DELETE_HOLIDAY_CALENDAR_SUCCESS";

//Employee Educational Info
export const GET_EMP_EUCATIONAL_INFO = "GET_EMP_EUCATIONAL_INFO";
export const GET_EMP_EUCATIONAL_INFO_SUCCESS =
  "GET_EMP_EUCATIONAL_INFO_SUCCESS";
export const ADD_EMP_EUCATIONAL_INFO = "ADD_EMP_EUCATIONAL_INFO";
export const ADD_EMP_EUCATIONAL_INFO_SUCCESS =
  "ADD_EMP_EUCATIONAL_INFO_SUCCESS";
export const UPDATE_EMP_EUCATIONAL_INFO = "UPDATE_EMP_EUCATIONAL_INFO";
export const UPDATE_EMP_EUCATIONAL_INFO_SUCCESS =
  "UPDATE_EMP_EUCATIONAL_INFO_SUCCESS";
export const DELETE_EMP_EUCATIONAL_INFO = "DELETE_EMP_EUCATIONAL_INFO";
export const DELETE_EMP_EUCATIONAL_INFO_SUCCESS =
  "DELETE_EMP_EUCATIONAL_INFO_SUCCESS";

//Qualification List
export const GET_EMP_QUALIFICATION = "GET_EMP_QUALIFICATION";
export const GET_EMP_QUALIFICATION_SUCCESS = "GET_EMP_QUALIFICATION_SUCCESS";

//Work Experience List
export const GET_EMP_WORKEXPERIENCE = "GET_EMP_WORKEXPERIENCE";
export const GET_EMP_WORKEXPERIENCE_SUCCESS = "GET_EMP_WORKEXPERIENCE_SUCCESS";

//Previous Company Details
export const GET_EMP_PREVIOUS_COMPANY_DETAILS =
  "GET_EMP_PREVIOUS_COMPANY_DETAILS";
export const GET_EMP_PREVIOUS_COMPANY_DETAILS_SUCCESS =
  "GET_EMP_PREVIOUS_COMPANY_DETAILS_SUCCESS";
export const ADD_PREVIOUS_COMPANY_DETAILS = "ADD_PREVIOUS_COMPANY_DETAILS";
export const ADD_PREVIOUS_COMPANY_DETAILS_SUCCESS =
  "ADD_PREVIOUS_COMPANY_DETAILS_SUCCESS";
export const UPDATE_PREVIOUS_COMPANY_DETAILS =
  "UPDATE_PREVIOUS_COMPANY_DETAILS";
export const UPDATE_PREVIOUS_COMPANY_DETAILS_SUCCESS =
  "UPDATE_PREVIOUS_COMPANY_DETAILS_SUCCESS";
export const DELETE_PREVIOUS_COMPANY_DETAILS =
  "DELETE_PREVIOUS_COMPANY_DETAILS";
export const DELETE_PREVIOUS_COMPANY_DETAILS_SUCCESS =
  "DELETE_PREVIOUS_COMPANY_DETAILS_SUCCESS";

//Previous ProjectList
export const GET_EMP_PREVIOUS_PROJECT_DETAILS =
  "GET_EMP_PREVIOUS_PROJECT_DETAILS";
export const GET_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS =
  "GET_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS";
export const ADD_EMP_PREVIOUS_PROJECT_DETAILS =
  "ADD_EMP_PREVIOUS_PROJECT_DETAILS";
export const ADD_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS =
  "ADD_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS";
export const UPDATE_EMP_PREVIOUS_PROJECT_DETAILS =
  "UPDATE_EMP_PREVIOUS_PROJECT_DETAILS";
export const UPDATE_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS =
  "UPDATE_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS";
export const DELETE_EMP_PREVIOUS_PROJECT_DETAILS =
  "DELETE_EMP_PREVIOUS_PROJECT_DETAILS";
export const DELETE_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS =
  "DELETE_EMP_PREVIOUS_PROJECT_DETAILS_SUCCESS";

// Projects action type.
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_PROJECT_LIST_SUCCES = "GET_PROJECT_LIST_SUCCES";
export const GET_PROJECT_LIST_OF_EMPLOYEE = "GET_PROJECT_LIST_OF_EMPLOYEE";
export const GET_PROJECT_LIST_OF_EMPLOYEE_SUCCESS =
  "GET_PROJECT_LIST_OF_EMPLOYEE_SUCCESS";
export const GET_SELECT_PROJECT = "GET_SELECT_PROJECT";
export const GET_SELECT_PROJECT_SUCCESS = "GET_SELECT_PROJECT_SUCCESS";
export const ADD_PROJECT_LEADER = "ADD_PROJECT_LEADER";
export const ADD_PROJECT_MEMBER = "ADD_PROJECT_MEMBER";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const DEL_PROJECT = " DEL_PROJECT";
export const DEL_PROJECT_SUCCESS = " DEL_PROJECT_SUCCESS";
// Skill action type.
export const GET_SKILL = "GET_SKILL";
export const GET_SKILL_SUCCESS = "GET_SKILL_SUCCESS";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const DEL_SKILL = "DEL_SKILL";
export const DEL_SKILL_SUCCESS = "DEL_SKILL_SUCCESS";
// payroll action type.
export const GET_PAYROLL_ITEM = "GET_PAYROLL_ITEM";
export const GET_PAYROLL_ITEM_SUCCESS = "GET_PAYROLL_ITEM_SUCCESS";
export const ADD_PAYROLL_ITEM = "ADD_PAYROLL_ITEM";
export const ADD_PAYROLL_ITEM_SUCCESS = "ADD_PAYROLL_ITEM_SUCCESS";
export const UPDATE_PAYROLL_ITEM = "UPDATE_PAYROLL_ITEM";
export const UPDATE_PAYROLL_ITEM_SUCCESS = "UPDATE_PAYROLL_ITEM_SUCCESS";
export const DEL_PAYROLL_ITEM = "DEL_PAYROLL_ITEM";
export const DEL_PAYROLL_ITEM_SUCCESS = "DEL_PAYROLL_ITEM_SUCCESS";

// Ticket action type.
export const GET_ALL_TICKET = "GET_ALL_TICKET";
export const GET_ALL_TICKET_SUCCESS = "GET_ALL_TICKET_SUCCESS";
export const GET_TICKET_BY_ID = "GET_TICKET_BY_ID";
export const GET_TICKET_BY_ID_SUCCESS = "GET_TICKET_BY_ID_SUCCESS";
